name: Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag name

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.tag }}',
              sha: context.sha
            })
