name: Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag name

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: touchlab/autoversion-finishrelease@main
        id: autoversion-finishrelease
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        with:
          commitMessage: "release for ${{ inputs.tag }}"
          tagMessage: "release version ${{ inputs.tag }}"
          tagVersion: ${{ inputs.tag }}
          branchName: "main"
